FROM python:3.9-slim

WORKDIR /app

# Install dependencies
COPY ./app/services/transcriptions/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application files
COPY ./app/services/transcriptions .

# Keep the container running
CMD ["python", "-u", "service.py"] 