        'truefire' => [
            'driver' => 'mysql',
            'url' => env('TF_DATABASE_URL'),
            'host' => env('TF_DB_HOST', '127.0.0.1'),
            'port' => env('TF_DB_PORT', '3306'),
            'database' => env('TF_DB_DATABASE', 'truefire'),
            'username' => env('TF_DB_USERNAME', 'root'),
            'password' => env('TF_DB_PASSWORD', ''),
            'unix_socket' => env('TF_DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('TF_MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ], 
        
        'channels' => [
            'driver' => 'mysql',
            'url' => env('CH_DATABASE_URL'),
            'host' => env('CH_DB_HOST', '127.0.0.1'),
            'port' => env('CH_DB_PORT', '3306'),
            'database' => env('CH_DB_DATABASE', 'channels'),
            'username' => env('CH_DB_USERNAME', 'root'),
            'password' => env('CH_DB_PASSWORD', ''),
            'unix_socket' => env('CH_DB_SOCKET', ''),
            'charset' => 'utf8mb4',
            'collation' => 'utf8mb4_unicode_ci',
            'prefix' => '',
            'prefix_indexes' => true,
            'strict' => true,
            'engine' => null,
            'options' => extension_loaded('pdo_mysql') ? array_filter([
                PDO::MYSQL_ATTR_SSL_CA => env('CH_MYSQL_ATTR_SSL_CA'),
            ]) : [],
        ], 